BEGIN;

UPDATE domains SET specific='{"Nibbler": {"rules": {"b": [{"name": "span", "class": "post-b"}, {"name": "b"}], "h2": [{"name": "h2"}], "h3": [{"name": "h3"}], "h1": [{"name": "h1"}, {"name": "span", "class": "post-align"}], "h4": [{"name": "h4"}], "i": [{"name": "fieldset", "class": "attach"}], "sp": [{"name": "div", "class": "sp-wrap"}]}, "category": {"0": [], "1": [], "2": [], "3": [], "4": [], "5": []}, "xpath_to_source": "(//div[@class=\\"post_body\\"])[1]", "xpath_to_torrent": "(//div[@class=\\"post_body\\"])[1]/fieldset/legend", "xpath_to_category": "//span[@class=\\"brand-bg-white\\"]/a[last()]/@href"}}' where id=1; --rutracker.org
UPDATE domains SET specific='{"Nibbler": {"rules": {"b": [{"style": "font-weight: bold", "name": "span"}], "h2": [{"name": "h2"}], "h3": [{"name": "h3"}], "h1": [{"name": "h1"}, {"style": "font-size: 20px; line-height: normal", "name": "span"}], "h4": [{"name": "h4"}], "i": [{"style": "padding: 3px", "name": "td", "colspan": "3", "align": "center", "valign": "middle", "class": "genmed"}]}, "category": {"0": [], "1": [], "2": [], "3": [], "4": [], "5": []}, "xpath_to_source": "(//td[@class=\\"row1\\"])[2]/table[not(@id)]", "xpath_to_torrent": "//span[@class=\\"genmed\\"]/b/a", "xpath_to_category": "html/body/div[1]/table/tbody/tr[2]/td/table/tbody/tr/td/table[2]/tbody/tr/td[2]/span/a[last()]/@href"}}' where id=2; --nnm-club.me
UPDATE domains SET specific='{"Nibbler": {"rules": {"b": [{"name": "b"}], "h2": [{"name": "h2"}], "h3": [{"name": "h3"}], "h1": [{"name": "h1"}], "h4": [{"name": "h4"}], "i": [{"name": "fieldset", "class": "attach"}]}, "category": {"0": [], "1": [], "2": [], "3": [], "4": [], "5": []}, "xpath_to_source": "(//div[@class=\\"post_body\\"])[1]", "xpath_to_torrent": "(//div[@class=\\"post_body\\"])[1]/div/fieldset/legend", "xpath_to_category": "(//td[@class=\\"nav w100\\"])[1]/a[last()]/text()"}}' where id=3; --tapochek.net
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}], "h2": [{"name": "h2"}], "b": [{"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "xpath_to_source": "//div[@class=\\"pT\\"]", "xpath_to_category": "(//div[@itemtype=\\"http://data-vocabulary.org/Breadcrumb\\"])[last()-1]/a[@itemprop=\\"url\\"]/span[@itemprop=\\"title\\"]/text()"}}' where id=4; --tfile.me
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}], "h2": [{"name": "h2"}], "b": [{"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "xpath_to_source": "//div[@id=\\"info\\"]", "xpath_to_category": "(//p[@class=\\"tags\\"])[1]/a[1]/text()"}}' where id=5; --torrentino.com
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}], "h2": [{"name": "h2"}], "b": [{"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "xpath_to_source": "//td[@class=\\"info\\"]", "xpath_to_category": "(//div[@class=\\"margin\\"])[1]/a[1]/text()"}}' where id=6; --fast-torrent.ru
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}], "h2": [{"name": "h2"}], "b": [{"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "xpath_to_source": "//div[@class=\\"mn1_content\\"]/div[@class=\\"bx1\\" or @class=\\"bx1 justify\\"]", "xpath_to_category": "//img[@class=\\"cat_img_r\\"]/@src"}}' where id=7; --kinozal.tv
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}], "h2": [{"name": "h2"}], "b": [{"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "xpath_to_source": "//div[@class=\\"info\\" or @class=\\"item-info-bottom\\"]", "xpath_to_category": 0}}' where id=8; --megashara.com
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}], "h2": [{"name": "h2"}], "b": [{"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "xpath_to_source": "//div[@class=\\"mid\\"]/div[1]", "xpath_to_category": "(//div[@class=\\"block_head\\"])[1]/text()"}}' where id=9; --lostfilm.tv (одни сериалы)
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}], "h2": [{"name": "h2"}], "b": [{"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "xpath_to_source": "//div[@class=\\"description\\"]", "xpath_to_category": 0}}' where id=10; --torrentino.net
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}], "h2": [{"name": "h2"}], "b": [{"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "xpath_to_source": "//div[@class=\\"news-content\\"]", "xpath_to_category": "//span[@class=\\"n-cat\\"]/h2/a/text()"}}' where id=11; --hdreactor.org
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}], "h2": [{"name": "h2"}], "b": [{"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "xpath_to_source": "//div[@id=\\"dle-content\\"]/table", "xpath_to_category": "//td[@class=\\"titlestext\\"]/a/h1[@style=\\"font-size: 12px;\\"]/text()"}}' where id=12; --sharlet.net (Надо вытащить из строки слово сериал или фильм, другого быть не может там
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}], "h2": [{"name": "h2"}], "b": [{"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "xpath_to_source": "//td[@class=\\"outer\\"]", "xpath_to_category": "//td[@class=\\"outer\\"]/table[2]/tbody/tr[10]/td[@align=\\"left\\"]/text()"}}' where id=13; --uniongang.tv  ((Надо вытащить из строки слово сериал или фильм и тд)
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}], "h2": [{"name": "h2"}], "b": [{"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "xpath_to_source": "(//div[@id=\\"left-column\\"])[1]/*[not(@style=\\"width:100%;\\")]", "xpath_to_category": 4}}' where id=14; --sound-park.ru (только музыка)
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}], "h2": [{"name": "h2"}], "b": [{"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "xpath_to_source": "//div[@class=\\"detailsMain\\"]", "xpath_to_category": 0}}' where id=15; --bit2bit.org
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}], "h2": [{"name": "h2"}], "b": [{"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "xpath_to_source": "(//div[@class=\\"post_body\\"])[1]", "xpath_to_category": "(//span[@itemtype=\\"http://data-vocabulary.org/Breadcrumb\\"])[last()]/a[@itemprop=\\"url\\"]/span[@itemprop=\\"title\\"]/text()"}}' where id=16; --unionpeer.org
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}], "h2": [{"name": "h2"}], "b": [{"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "xpath_to_source": "//div[@class=\\"maincont clr\\"]", "xpath_to_category": "(//li[@class=\\"icat\\"])[1]/a/text()"}}' where id=17; --torzona.ru
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}], "h2": [{"name": "h2"}], "b": [{"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "xpath_to_source": "(//div[@class=\\"short-block\\"])[1]/*[not(@class=\\"commentS-block\\")]", "xpath_to_category": 0}}' where id=18; --newserial.tv
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}], "h2": [{"name": "h2"}], "b": [{"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "xpath_to_source": "(//div[@class=\\"f-story\\"])[1]", "xpath_to_category": 0}}' where id=19; --torzone.org
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}], "h2": [{"name": "h2"}], "b": [{"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "xpath_to_source": "(//div[@class=\\"postbody\\"])[1]", "xpath_to_category": "//p[@class=\\"breadcrumbs\\"]/a[last()]/text()"}}' where id=20; --rus-media.org

COMMIT;

