BEGIN;

UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}, {"name": "span", "class": "post-align"}], "h2": [{"name": "h2"}], "b": [{"name": "span", "class": "post-b"}, {"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "path_to_source": {"position": "1", "name": "div", "class": "post_body"}, "path_to_category": {"child": {"position": "-1", "name": "a", "target": "text"}, "name": "td", "class": "nav w100 pad_2"}}}' where id=1; --rutracker.org
-- right for rutracker, and copied for other trackers. It doesnt work with trackers below
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}, {"name": "span", "class": "post-align"}], "h2": [{"name": "h2"}], "b": [{"name": "span", "class": "post-b"}, {"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "path_to_source": {"position": "1", "name": "div", "class": "post_body"}, "path_to_category": {"child": {"position": "-1", "name": "a", "target": "text"}, "name": "td", "class": "nav w100 pad_2"}}}' where id=2; --nnm-club.me
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}, {"name": "span", "class": "post-align"}], "h2": [{"name": "h2"}], "b": [{"name": "span", "class": "post-b"}, {"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "path_to_source": {"position": "1", "name": "div", "class": "post_body"}, "path_to_category": {"child": {"position": "-1", "name": "a", "target": "text"}, "name": "td", "class": "nav w100 pad_2"}}}' where id=3; --tapochek.net
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}, {"name": "span", "class": "post-align"}], "h2": [{"name": "h2"}], "b": [{"name": "span", "class": "post-b"}, {"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "path_to_source": {"position": "1", "name": "div", "class": "post_body"}, "path_to_category": {"child": {"position": "-1", "name": "a", "target": "text"}, "name": "td", "class": "nav w100 pad_2"}}}' where id=4; --tfile.me
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}, {"name": "span", "class": "post-align"}], "h2": [{"name": "h2"}], "b": [{"name": "span", "class": "post-b"}, {"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "path_to_source": {"position": "1", "name": "div", "class": "post_body"}, "path_to_category": {"child": {"position": "-1", "name": "a", "target": "text"}, "name": "td", "class": "nav w100 pad_2"}}}' where id=5; --torrentino.com
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}, {"name": "span", "class": "post-align"}], "h2": [{"name": "h2"}], "b": [{"name": "span", "class": "post-b"}, {"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "path_to_source": {"position": "1", "name": "div", "class": "post_body"}, "path_to_category": {"child": {"position": "-1", "name": "a", "target": "text"}, "name": "td", "class": "nav w100 pad_2"}}}' where id=6; --fast-torrent.ru
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}, {"name": "span", "class": "post-align"}], "h2": [{"name": "h2"}], "b": [{"name": "span", "class": "post-b"}, {"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "path_to_source": {"position": "1", "name": "div", "class": "post_body"}, "path_to_category": {"child": {"position": "-1", "name": "a", "target": "text"}, "name": "td", "class": "nav w100 pad_2"}}}' where id=7; --kinozal.tv
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}, {"name": "span", "class": "post-align"}], "h2": [{"name": "h2"}], "b": [{"name": "span", "class": "post-b"}, {"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "path_to_source": {"position": "1", "name": "div", "class": "post_body"}, "path_to_category": {"child": {"position": "-1", "name": "a", "target": "text"}, "name": "td", "class": "nav w100 pad_2"}}}' where id=8; --megashara.com
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}, {"name": "span", "class": "post-align"}], "h2": [{"name": "h2"}], "b": [{"name": "span", "class": "post-b"}, {"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "path_to_source": {"position": "1", "name": "div", "class": "post_body"}, "path_to_category": {"child": {"position": "-1", "name": "a", "target": "text"}, "name": "td", "class": "nav w100 pad_2"}}}' where id=9; --lostfilm.tv (одни сериалы)
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}, {"name": "span", "class": "post-align"}], "h2": [{"name": "h2"}], "b": [{"name": "span", "class": "post-b"}, {"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "path_to_source": {"position": "1", "name": "div", "class": "post_body"}, "path_to_category": {"child": {"position": "-1", "name": "a", "target": "text"}, "name": "td", "class": "nav w100 pad_2"}}}' where id=10; --torrentino.net
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}, {"name": "span", "class": "post-align"}], "h2": [{"name": "h2"}], "b": [{"name": "span", "class": "post-b"}, {"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "path_to_source": {"position": "1", "name": "div", "class": "post_body"}, "path_to_category": {"child": {"position": "-1", "name": "a", "target": "text"}, "name": "td", "class": "nav w100 pad_2"}}}' where id=11; --hdreactor.org
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}, {"name": "span", "class": "post-align"}], "h2": [{"name": "h2"}], "b": [{"name": "span", "class": "post-b"}, {"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "path_to_source": {"position": "1", "name": "div", "class": "post_body"}, "path_to_category": {"child": {"position": "-1", "name": "a", "target": "text"}, "name": "td", "class": "nav w100 pad_2"}}}' where id=12; --sharlet.net (Надо вытащить из строки слово сериал или фильм, другого быть не может там
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}, {"name": "span", "class": "post-align"}], "h2": [{"name": "h2"}], "b": [{"name": "span", "class": "post-b"}, {"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "path_to_source": {"position": "1", "name": "div", "class": "post_body"}, "path_to_category": {"child": {"position": "-1", "name": "a", "target": "text"}, "name": "td", "class": "nav w100 pad_2"}}}' where id=13; --uniongang.tv  ((Надо вытащить из строки слово сериал или фильм и тд)
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}, {"name": "span", "class": "post-align"}], "h2": [{"name": "h2"}], "b": [{"name": "span", "class": "post-b"}, {"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "path_to_source": {"position": "1", "name": "div", "class": "post_body"}, "path_to_category": {"child": {"position": "-1", "name": "a", "target": "text"}, "name": "td", "class": "nav w100 pad_2"}}}' where id=14; --sound-park.ru (только музыка)
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}, {"name": "span", "class": "post-align"}], "h2": [{"name": "h2"}], "b": [{"name": "span", "class": "post-b"}, {"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "path_to_source": {"position": "1", "name": "div", "class": "post_body"}, "path_to_category": {"child": {"position": "-1", "name": "a", "target": "text"}, "name": "td", "class": "nav w100 pad_2"}}}' where id=15; --bit2bit.org
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}, {"name": "span", "class": "post-align"}], "h2": [{"name": "h2"}], "b": [{"name": "span", "class": "post-b"}, {"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "path_to_source": {"position": "1", "name": "div", "class": "post_body"}, "path_to_category": {"child": {"position": "-1", "name": "a", "target": "text"}, "name": "td", "class": "nav w100 pad_2"}}}' where id=16; --unionpeer.org
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}, {"name": "span", "class": "post-align"}], "h2": [{"name": "h2"}], "b": [{"name": "span", "class": "post-b"}, {"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "path_to_source": {"position": "1", "name": "div", "class": "post_body"}, "path_to_category": {"child": {"position": "-1", "name": "a", "target": "text"}, "name": "td", "class": "nav w100 pad_2"}}}' where id=17; --torzona.ru
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}, {"name": "span", "class": "post-align"}], "h2": [{"name": "h2"}], "b": [{"name": "span", "class": "post-b"}, {"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "path_to_source": {"position": "1", "name": "div", "class": "post_body"}, "path_to_category": {"child": {"position": "-1", "name": "a", "target": "text"}, "name": "td", "class": "nav w100 pad_2"}}}' where id=18; --newserial.tv
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}, {"name": "span", "class": "post-align"}], "h2": [{"name": "h2"}], "b": [{"name": "span", "class": "post-b"}, {"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "path_to_source": {"position": "1", "name": "div", "class": "post_body"}, "path_to_category": {"child": {"position": "-1", "name": "a", "target": "text"}, "name": "td", "class": "nav w100 pad_2"}}}' where id=19; --torzone.org
UPDATE domains SET specific='{"Nibbler": {"rules": {"h1": [{"name": "h1"}, {"name": "span", "class": "post-align"}], "h2": [{"name": "h2"}], "b": [{"name": "span", "class": "post-b"}, {"name": "b"}], "h4": [{"name": "h4"}], "h3": [{"name": "h3"}]}, "path_to_source": {"position": "1", "name": "div", "class": "post_body"}, "path_to_category": {"child": {"position": "-1", "name": "a", "target": "text"}, "name": "td", "class": "nav w100 pad_2"}}}' where id=20; --rus-media.org

COMMIT;